;-*- mode: Org; fill-column: 100;-*-
kski
nikkei 225
csi300

eu
ftse 100
cac 40
dax

Процентное изменение: *((V2-V1)/V1) × 100*. Где V1 – старое значение, а V2 – новое
* english
- Financial institutions [faɪˈnænʃəl] [ɪnstɪˈtjuːʃn] :: banking institutions
- deposit [dɪˈpɔzɪt] :: вклад Depository institutions - кредитная организация
- loan [ləʊn] :: ссыды, кредиты
- fraud  [frɔːd] :: мошенничество
- swipe [swaɪp] :: Swipe your card, please. Paid $300,000 on swipe fees. swipe machines - проводя черной полосой карты
- equity [ˈekwɪtɪ] :: капитал
- retail store [ˈriːteɪl] [stɔːz] :: розничный магазин.
- pricing [ˈpraɪsɪŋ] :: ценообразование
- Stock market  [stɒk ˈmɑːkɪt] :: фондовая биржа
- stock :: акция
- share :: акция
- outstanding shares :: размещенные акции
- bonds :: облигации
- futures :: фьючерсы
- commodity  /kəˈmädədē/ :: товар, сырье
- security  [sɪˈkjʊərɪtɪ] :: ценная бумага
- equity  [ˈekwɪtɪ] :: капитал
- revenue [ˈrevɪnjuː] :: доход
  - net income [net ˈɪnkʌm] :: чистый доход
- collateral :: залог, обпеспечени
- margin trading /ˈmärjən/ :: the collateral that a holder of a financial instrument has to deposit
 with a counterparty/broker/echange organization to cover some or all of the credit risk the holder
 poses for the counterparty.
* личные правила
*Покупай на историях(несколько сценариев) - продавай на фактах(сценарии исчерпаны))* @ RBK
 - сначала определи это какое событие запланированное или случайное, если запланированное то как
*Не делать ставку без стоплоса!!!*
*Всегда иметь свободные деньги на случай крупной новости и временной паники*
*Есть два диапазона - долгосрочный и краткосрочный, на краткосрочном технический анализ*
*глобальные новости развиваются по дням*
*сначала реакция проффесионалов, потом всех*

** прогнозирование
 1) поиск коррекционного отката, по

 Предвидеть новостные сигналы и сопоставить для каждого движение вверхи или! вниз

 *тренд резко не меняет направление - нужна фаза стагнации или отката*

 *контр-трендово не шортят - риск*

 *риск к прибыли должен быть больше чем 3 к 1*

 *On balance volume - не работает на фьючерсных контрактах*

 *после стопосъемного шипа тренд идет в противоположную сторону*

 *медвежья дивиргения - рост - признак слабости(RSI, OnBalanceVolume) - будет падение*
 *бычья дивиргенция - падание - признак слабости - будет рост*

 *три волны падения и с коррекциями - завершение падающего тренда*

 *разворотный паттерн - двойное основание*

 - фон диктует тренд
 - корреляция диктует тренд
 - 4 процента - бери
 - коррекция - приритет над трендом имеет 15 минутная 200 дневная средняя
 - кризис - покупают тяжелую промушленность и золото
 - не кризис - инновации
 - с утра - по тренду - потом - коррекция
 - перед рискованным событием увеличивается волатильность, тренд сохраняется
 - сходящийся треугольник - после резкого испуга.
 - боковик - готовится к скачку

*** бабы говорят
 - Если волатильность низкая, значит книга заказов на бирже сбалансирована, то есть цена не изменится, пока
   торговый объем останется прежним. Если же внезапно увеличится число продавцов или покупателей, то цена может
   резко измениться.
 - Если волатильность высокая, входить в рынок очень опасно. Нужно понимать, что сейчас уже поезд упущен, и
   ждать следующего удобного момента для входа в рынок.
 - Если волатильность снижается. Низкая и снижающаяся волатильность характерны для роста цены. Если
   волатильность продолжает снижаться, это может быть «бычьим» признаком.
 - Если волатильность растет, это говорит об усилении нервозности на рынке. Рынок предлагает хорошие
   возможности для открытия позиций, но и риски потерь становятся выше.

** Investing Tips
1) Patience - Understand risks
2) Diversification
3) Planning - Invest don’t speculate
4) Long-term - Determine your goals
5) research - Stick to your plan
6) risk/reward - Invest regularly
7) Don't be afraid to ask for help
* top_русорсов
- https://smart-lab.ru
- http://blog.gazprombank.investments/
- раскрытие информации https://e-disclosure.ru
* брокер
** счет у брокера
денежные средства хранятся на обособленных счетах брокеров, т.е. брокер к ним не имеет юридического
доступа, а значит, не может расходовать или переводить данные средства. Кроме того, на эти средства
не может быть наложен арест по обязательствам брокера. Т.е. банкротство брокера с юридической точки
зрения также не распространяется и на денежную часть Ваших средств.
** депозиторий для акций
Номинальный держатель — это такое лицо, на счет которого записаны акции, реальным владельцем которых
оно не является. Например депозитарий. Это лицо, в свою очередь, хранит информацию о реальных
владельцах.
- Ценные бумаги хранятся не на счетах брокера, а на счетах депо в депозитарии.
- Это отдельная организация, обладающая лицензией ЦБ РФ на ведение депозитарной деятельности.
- Обычно услуги депозитария включены в стоимость услуг брокера, а сам депозитарий является
  обособленным подразделением брокера

 Если Вы заключили с брокером *соглашение* о предоставлении Ваших *ценных бумаг в залог для операций
  брокера*, то в данном случае Вы рискуете потерять свои ценные бумаги при банкротстве брокера.

Компания-эмитент
(например «Эпл»)
↑
Компания-регистратор
(т. н. transfer agent)
↑
Американский центральный депозитарий
(DTC)
↑
Цепочка других депозитариев
↑
Депозитарий Брокера или отдельный
↑
Клиент
(вы)

* QUICK
1) Система заказ данных
2) окна
3) установить горячую клавишу для "Изменить интервал в диаграмма"
** таблица текущих торгов
- Класс
- Инструмент сокр
- Цена послед
- % измен закр
- макс цена
- мин цена
- оборот
- ISIN - ?????
- валюта
** TODO диаграмма
** Tinkoff mobile apple
RSI базовые значения уровней 70 30
MA 25 и 50
EMA 25 и 50
MACD
Stochastic - используются уровни 80- перекупленности и 20 - ориентир перепроданности

** горячие клавиши
- Ctrl+E редактировать окно/график
- F6 в стакане - стоп заявка
- Alt+1/2/3/4/5 - переключение между закладками
- Ctrl+N - копировать окно
- Ctrl+H - редактор горячих клавиш
** заявки
 *stop-limit*
 - Sell - если слишком сильно упадет ПРОДАЕМ
   - проскальзывание - цену продажи выставляем МЕНЬШЕ предела, чтобы успеть найти покупателей
 - Buy - если ожидаем пробой вверх ПОКУПАЕМ
   - проскальзывание - цену покупки выставляем БОЛЬШЕ предела, чтобы успеть найти продавцов

 *take-profit* -
 - Sell - если достаточно выросла ПРОДАЕМ (lot 10 - в одном лоте 10 акций)
   - offset from max - маленькие падения в низ в течении которого заявка не будет активироваться
     - слишком маленькое - продажа сразу на первой волне (2 копеек)
     - слишком большое - слишком сильно упадет после большого скачка и будет продана по меньшей цене (3копеек)
   - protective spread - отступ вниз по которой активированная заявка попадет в рынок (как проскальзывание)
 - Buy - для short

 *стоп-лосс*
 - ниже нижнего price-channel
 - особенно важны при покупке выше средней-200-дневной
 - в кризис стоп-лоссы смитаются волатильностью
* участники
доля биржевых операций профучастников
- 77% - фондовом рынке
- 83% - рынке репо
- 53% - валютном рынке


Вообще
- Высокочастотные роботы (HFT)
- Скальперы - внутри дня
  - на лучший бид и  потом сразу на лучший аском
  - отскок от крупного офферта
  - после разъедания крупного офферта будет резкое движение в его сторону от стоп-лосов
- *Маркетмейкеры и торговые алгоритмы* Маркетмейкеры - продают кода покупают и покупают когда
  продают - пользуются льготами биржи
- *Частные инвесторы и профессиональные трейдеры*
- *Крупные игроки и инвестиционные фонды*

* новостные каналы
- РБК
- интерфакс - зона справедливых цен
- блумберг
- новости IT госрегулирование https://www.gazeta.ru/tech/government.shtml
- Российская Газета https://rg.ru/tema/ekonomik/
* стибильность банка
https://mainfin.ru/banki/rating?sort=assets_netto
Основные показатели
- Активы нетто, тыс. руб.
- Депозиты физ.лиц, тыс. руб.
- Кредиты физ.лиц, тыс. руб.

Уралсиб https://www.banki.ru/banks/ratings/?BANK_ID=63520
- активы    531 386 135
* теория
- *Фьючерс* (futures contract или англ. futures) - контрактами на покупку или продажу в будущем базового актива
- (Short) *шорт* (сокращенное от английского short selling) – это продажа участником рынка акций или другого
  инвестиционного инструмента, которыми он не владеет
- Лонговать - купить, подождать пока цена понимится
- зона поддержки - нижняя price channel

C 2009 брокерам запрещено допускать шорты по акциям цена которых снизилась больше 3% от стоимости закрытия

Пики торгов -  на открытии и в момент выхода статистики
** Финансовые инструменты
- Рыночные инструменты:
  - биржевые инструменты
    - Московская биржа
    - Биржа СПБ
    - NYSE
    - LSE
  - внебиржевые
    - ФОРЕКС - размер сделок $2 млн.
      - брокер - для крупных клиентов
      - диллер - ларек
    - еврооблигации - есть и на московской бирже
- ПИФы и доверительное управление
- страховые продукты
  - накопительное страхование  НСЖ и снвестиционно ИСЖ
  - unit linked (ULIP) - с иностранной компанией - страховка и инвестиционный фонд


Ценные бумаги
- долговые
  - облигации
  - векселя
  - деньги
  - депозиты
- долевые
  - акции
  - паи

** Япо́нские све́чи
Отражают не только цену, но и её волатильность
- Верхняя и нижняя граница тени отображает максимум и минимум цены за соответствующий период.
- Границы тела отображают цену открытия и закрытия.

** Trading System
https://relaxedtrader.com/trading-system-works-future/

good:
- Lots of samples
- Out of sample testing looks like in sample testing
- Factor in commission and slippage
- System trades a with lower number of shares in volatile markets

Minimum Requirements For A Robust System:
- Minimum 100 trades
- At least 10 years of data
- Statistical significance of 30 ( profit factor * number of samples ^ 0.5 )
- 20% of data used for "out of sample" (OOS) testing
- OOS Profit Factor  / In Sample Profit Factor >= 70%
- Net profit / Max drawdown >= 10
- Profit factor >= 2

System Score = Profit Factor * Number Of Trades ^ ( 0.5 )  * ( Net Profit / Max Drawdown ) * ( Out Of Sample Profit Factor / In Sample Profit Factor )


*Profit factor* = (gross winning trades) / (gross losing trades) or = (Win rate x average win) / (Loss rate x average loss)

Main trading systems:
- *Mean Reversion* - следим за средней показывающй тренд и когда она меняет направление на определенное
  значение - покупаем или продаем. - does not work with a trend following market
- *trend following* - следуем по тренду не отклоняясь

The only real Holy Grail in trading is the use of multiple systems trading different asset classes.
** books - спекулятивный трейдинг
- Технический анализ финансовых рынков - Джон Дж. Мэрфи (Азбука технического анализа)
- Чарльз ЛеБо, Дэвид В. Лукас "Компьютерный анализ фьючерсных рынков" (Индикаторный технический
  анализ, без фигур)
- В. Тарп "Трейдинг - ваш путь к финансовой свободе" (универсальная)
- Психология трейдинга. Инструменты и методы принятия решений. Бретт Стинбарджер (психологические
  проблемы)
- Куртис Фейс. Путь Черепах. Из дилетантов в легендарные трейдеры (поучительная история, дух спекулятивного трейдинга)
** https://www.youtube.com/watch?v=wY7DG0wM8j0
- 60% - Психология трейдинга
- 30% - определение размера позиции - risk management, money management
- 10% - развитость системы - точка входа и выхода

Неудачи - игнорирование 60 30 и не имеют системы

Торговая система - это набор правил - алгоритм действия трейдера в рыночных ситуациях
- момент открытия закрытия позиции
- размер открываемой позиции

Торговая система - условная система отсчета, система координат *относительно которой* трейдер 1)
определяет ситуацию 2) принимает решение

Торговая система выстраенная на основе:
- технического анализа - спекулятивная (пример Ричард Деннис)
- фундаментального анализа - инвестиционная (пример Уорен Баффет)

Создание торговой системы:
1) выбор стратегии
2) подбор команлы тех индикаторов под стратегию. Каждый выполняет свою роль. Все - как единое целое.

** Пример торговой системы “Обзор рынка РФ” с Рустемом Ибрагимовым.
- годовая доходность ~50%
- максимальная просадка по счету 30% ниже 20% не опускался
- 60% сделок убыточно. 40% прибыльные - не количество а качество - выжать максимальную прибыль из сделки
- дисциплина - не каждый месяц или даже год

находим точку входа, берем точку выхода по скользящей средней или где видим и ждем, ставим стоп лос - период от недели до полугода
- не более 6% от капитала
** стакан
- биржевой стакан - дает нам информацию о лимитных заявках на рынке
- лента обезличенных сделок — о том, на какие объемы были заключены сделки по различным ценам.
** девольвация рубля
- Фьючерс "доллар/рубль" или Si
- ETF на еврооблигации российских корпоративных эмитентов (FXRU)
** CAPM Модель оценки финансовых активов (Capital Assets Pricing Model)
модель, описывающая связь ожидаемой доходности портфеля ценных бумаг со степенью его риска.

Согласно САРМ, инвесторы вознаграждаются за рыночный риск, но их нерыночный риск не
компенсируется. Модель САРМ является основой современной теории цен на финансовых рынках.
** Дивидендная отсечка - как причина падения цены (дивидендный гэп)

с утра 2 октября 2020 Сбербанк 8% обвал. пик - 10:00
- Последний день покупки - 1 окт 2020
- Дата закрытия реестра - 5 окт 2020

Дивиденды обычно указываются в рублях на одну акцию. Иногда в Доля дивидендов от чистой прибыли (по
МСФО).

дивиденды должны заплатить в течение 25 рабочих дней с даты фиксации реестра.

Информация о дивидендах:
- карточка эмитента на мос бирже https://www.moex.com/ru/listing/emidocs.aspx?id=1399
- На сайте центра обязательного раскрытия корпоративной информации. https://www.e-disclosure.ru/portal/company.aspx?id=564
- на офф сайте компании

Размер дивидендов решается на собрании акционеров:
- годовое общее собрание акционеров — ГОСА
- внеочередное общее собрание акционеров — ВОСА

*** пример
13 августа	Заседание совета директоров и публикация протокола с размером дивидендов
19 сентября	ВОСА, акционеры одобрили выплату дивидендов
20 сентября	Опубликована информация о дивидендах — размер и дата фиксации реестра
27 сентября	Последний день, когда можно купить акции, чтобы получить дивиденды (закладываем время на операции на самой бирже и выходные)
1 октября	Дата фиксации под дивиденды
9 октября	Деньги зачислены на брокерский счет
6 ноября	«Норильский никель» завершил выплаты
** Байбэк
- https://bcs-express.ru/buybacks
Байбэк – (от англ. buyback) обратный выкуп эмитентом собственных акций. Это ситуация, когда компания
выкупает акции у действующих акционеров на открытом рынке. По итогам данной процедуры количество
свободно обращающихся бумаг уменьшается, что в свою очередь может приводить к росту стоимости акций

* Инструменты
** облигации
время
- еще какие-то
- среднесрочные - до 5 лет
- долгосрочные более 5 лет

как выбирать
1 кредитный рейтинг
2 обеспечение - в случае банкротсвта
3 дюрация - насколько цента облигация  чувствительна к изменению процентной ставки

как заработать
купон - процент от номинации которая платится держателю
разница в цене
участие в первичном размещении - цена зависит от количечтва участников и эмитента

13 процентов, льгота не менее 3 лет

** ВДО высокодоходные облигации
https://овкладах.рф/obligatsii/vysokodohodnye/
два типа:
- биржевые
- коммерческие высокодоходные облигации.

Отрасли-лидеры по размещению ВДО:
- лизинг
- микрофинансовые организации
- девелопмент

Главная опасность – дефолт. Рыночного риска, как такового, нет
Источник: https://xn--80aaej2ags6d.xn--p1ai/obligatsii/vysokodohodnye/

* Секторы
коды всех акций https://www.moex.com/ru/marketdata/archive/#/engine=stock&market=index&data_type=trades&data_interval=current&data_format=csv&year=2020
- лидеры https://www.finam.ru/analysis/leaders/
- Отрасли https://www.finam.ru/analysis/bundle00008/?mode=0
  - https://www.finam.ru/analysis/bundle00004/?mode=0
** IT
https://investcafe.ru/blogs/64668638/posts/41984
| YNDX |  Яндекс|
| QIWI| QIWΙ|
Яндекс", МТС и "Ростелеком"


- Mail.ru Group (MCX:MAILDR)
- HeadHunter (NASDAQ:HHR)
- Ozon (NASDAQ:OZON)
- Яндекс MCX:YNDX)

    Яндекс – 10,724 млрд долларов
    Mail.ru Group – 5,362 млрд долларов
    AVITO – 3,85 млрд долларов
    Wildberries – 1,2 млрд долларов
    Ozon Group – 694 млн долларов
    HeadHunter – 299 млн долларов
    Ситилинк – 245 млн долларов
    2ГИС – 243 млн долларов
    Lamoda – 226 млн долларов
    ivi.ru – 204 млн долларов
    Aviasales – 196 млн долларов
    Profi.ru – 151 млн долларов
    ОнлайнТрейд.ру – 110 млн долларов
    Skyeng – 109 млн долларов
    1С-Битрикс – 106 млн долларов
    TalentTech – 97 млн долларов
    Циан Групп – 96 млн долларов
    B2B-Center – 95 млн долларов
    Superjob – 93 млн долларов
    YouDo – 88 млн долларов
** Строительство
ГК "Самолет", ГК "ПИК", Группы ЛСР и Группы "Эталон"

- ПАО  Группа ЛСР  ао (LSRG)  - редевелопмента  территории в  Москве, производства  стройматериалов, добычи  и
  переработки нерудных ископаемых, девелопмента и строительства недвижимости
- ПАО Группа Компаний ПИК (PIKK) - строительная компания ( доставка еды)

** металлургия
Золото
- Полюс
- Полиметалл
Ост
- Мечел ао/ ап
- ГМКНорНик - палладий, конкурент ЮАР
- Северсталь - конкурент ЕВРАЗ
- ММК
- НЛМК
- Распадская
- Алроса
- Русал
** нефть и газ
- Лукойл
- Газпром
- Роснефть
- Сургут ао/ап
- Татнефть ао/пр
- Новатек
- Газпромнефть
** Энергетика
- ИнтерРАО
- ФСК ЕЭС
- РусГидро
- Россети ао
- Мосэнерго
- ОГК-2
- Юнипро
- ТГК-1
- МРСК Ур
- Ленэнерго- п
** телекоммуникация
- Ростелеком
- МТС
- Мегафон
- Система
** банки
- Сбербанк
- ВТБ
- Мосбиржа
- Тиньков -TCSG- ТиСиЭс Груп Холдинг ПиЭлСи -  Т+: Акции и ДР
** нефтехимия
- Акрон
- Фосагро
- Уралкалий
- НКНХ ао/ап

разное
- AGRO гдр
- Аэрофлот
- Яндекс
- Дикси
- Детский мир
- Магнит
- ТМК
- Русолово
- ЛСР
- Лента
** фармацевтика
- iФармсинтез - полный цикл создания новых эффективных лекарственных средств
** кибербезопасность
- Positive Technologies MCX: POSI
** лесопромышленный
- Segezha Group - Сегежа Групп (Sgzh)
* Cрочный рынок
- https://www.bloomberg.com/markets/commodities
- https://www.moex.com/ru/derivatives/

Bloomberg Commodity Index
** теория
FORTS(«Фьючерсы и Опционы Российской Торговой Системы», Futures & Options of RTS). Это часть
Московской биржи и позволяет игрокам использовать в качестве рабочих инструментов фьючерсные и
опционные контракты.
** фьючерс
*Покупка фьючерса* - подешевели - убыток (ставка на рост)
- Представим, что вы купили 10 фьючерсов на акции по 5500 рублей и к моменту исполнения контракта акции стоят 5000 рублей.
- При поставочном контракте вы будете обязаны купить 10 акций по 5500 рублей. Вы потратите 55 000
  рублей, и в вашем портфеле появятся 10 акций общей стоимостью 50 000 рублей. Убыток 5000.
- При расчетном контракте у вас не появится никаких акций — биржа просто рассчитает ваш убыток и
  спишет со счета 5000 рублей.
- При поставочном нужно будет купить акции и если не хватит денег - штрафные санкции.

*Продажа* - подешевели - прибыль (ставка на падение)

*коды фьючерса*
- https://www.moex.com/a214
- CMY - C - код базового актива(2с), M - месяц FGHJKMNQUVXZ, Y - год 0-9 (2020=0)
- GAZR-9.19 Тикер базового актива, месяц и год исполнения контракта.

*базис фьючерсного контракта* - Разница между текущей ценой базового актива и соответствующей фьючерсной ценой
- бэквордация - фьючерс торгуется ниже цены базового актива
- контанго
*** характеристики фьючесов
 - *тип конртракта* (подтип инструмента)
   - Поставочный - при исполнении фьючерса вы обязаны купить непосредственно сам базовый актив.
   - Расчетный - происходит только финансовый расчет вашей сделки
*** популярные фьючерсы
https://www.moex.com/a214
https://greedisgood.one/fyuchersy-na-moskovskoy-birzhe

- RVI-1.21 (VIF1) - волатильность
- Si - курс доллар США – российский рубль

other
- ED - курс евро – доллар США
- Eu - курс евро – российский рубль
- GAZR
- LKOH
- MIX- or MX - Индекс МосБиржи
- RTS- or RI - Индекс РТС
- SBRF - ПАО Сбербанк (о.а.)

*** товары https://www.moex.com/s202
На сорт нефти Light Sweet Crude Oil	CL	—
На сорт нефти марки Brent	BR	—
Золото	GOLD	—
Серебро	SILV	—
Платина	PLT	—
Палладий	PLD	—
Алюминий	ALMN	—
Цинк	Zn	—
Никель	NI	—
Медь	Co	—
Сахар-сырец	SUGR
Золото	GLD	Поставочный
Серебро	SLV	—

Источник: https://greedisgood.one/fyuchersy-na-moskovskoy-birzhe
*** Фьючерсы на ОФЗ
2-летние	OFZ2	Поставочный
10-летние	OF10	—
15-летние	OF15	—
6-летние	OFZ6	—
4-летние	OFZ4	—
** опцион
покупка или продажа по фьючерсу обязательна, в то время как опцион предоставляет на них право (а не обязанность).
** Crude Oil
https://www.thebalance.com/trading-crude-oil-futures-809351
Производство
- бензин gasoline - примерно идет половина
- газ - natural gas
- heating oil - топочный мазут
- diesel fuel - поезда, судоходство, транспорт, тракторах
- jet fuel

Влияет
- affect 95% of transportation -﻿ That creates higher food prices
- impacts 45% of industrial products and around 20% of residential useю As a result, higher oil
  prices increase the cost of everything you buy, creating inflation.
- Burning oil or gasoline releases the carbon dioxide. It's created a greenhouse effect. -> global warming

Виды
- WTI West Texas Intermediate - WTI sells at a $3.00-$4.00 per barrel discount to Brent
- Brent Blend

* Валюты Currencies
** U.S. Dollar Index (USDX, DXY, DX, or, informally, the "Dixie") - relative to a basket of foreign
 currencies. (basket of U.S.)
- The Index goes up when the U.S. dollar gains "strength" when compared to other currencies
- value relative to following select currencies:
  - Euro (EUR), 57.6% weight
  - Japanese yen (JPY), 13.6%
  - Pound sterling (GBP), 11.9%
** валюты
- HKD - Hong Kong Dollar -  official currency of the Hong Kong Special Administrative Region
- CHN - Chinese Yuan Renminbi
** курс рубля
**Международный эффект Фишера пример USD/RUB**
1. текущий курс рубля
2. номинальная ставка в рублях ( гос. долг на требуемый горизонт)
3. номинальная ставка в доллорах ( гос. долг на требуемый горизонт)
они
- USD/RUB=75 руб / за 1 доллар
- ОФЗ 5 лет = 5.46%
- US Tr 5 лет = 0.32%

будущий курс на 5 лет = 75 * (1 + 0.0546)^5/ (1+0.0032)^5 = 96.28


* Индексы акций
https://www.moex.com/ru/index/IMOEX/about/
- all at one page https://www.moex.com/ru/data/?tid=3028
- heatmap https://www.moex.com/ru/indices/heatmap

VIX - Индекс волатильности и страха на рынке. CBOE Volatility Index
** рейтинги
Environmental social and governance (ESG) investing

Free Float Market Capitalization - the total dollar value of all of a company's outstanding shares
 at the current market price.
** опережающие индексы
- pmi
- business climat and activity
- новостные события  отчетов компаний двигают рынок вверх
* мировые индексы Биржи
- DXY - strength of dollar to major currencies

*RU*
- MOEXBC	голубые фишки
*индекс мос биржи и индекс ртс* - наиболее ликвидные 50, одинаковый состав
- IMOEX		индекс мос биржи - цена акций в рублях
- RTSI		РТС - цена акций в долларе
- MCXSM 	Индекс МосБиржи средней и малой капитализации
- MOEXINN	Индекс МосБиржи инноваций - в секторе "Рынок инноваций и инвестиций"
- RGBI		государственных облигаций (ОФЗ) Московской биржи.
- акции мира https://www.moex.com/ru/issue.aspx?board=TQTF&code=FXWO
- акции мира https://www.moex.com/ru/issue.aspx?board=TQTF&code=FXRW

*US*
- DJIA - Dow Jones - 30 крупнейших - 25% акций.
  - Наибольший вес у Boeing, UnitedHealth Group и McDonalds.
- S&P 500 - 505 крупнейших 70% акций.
  - Наибольший вес — у Microsoft, Apple и Amazon.
- NAsdaq100 - 100 технологические и инновационные компании биржи и биржи Nasdaq Exchange.
  - Наибольший вес у Microsoft, Amazon и Apple.
- Russell 2000 - 2000 наименьших компаний
*Europe*
- FTSE 100	Британия(Лондон) 101акц. наибольший вес у HSBC, Royal Dutch Shell и BP
- DAX		Германия  Frankfurt Stock Exchange - доходность. 30 компаний
- CAC 40	Франция Euronext Paris - 40 компаний
- Stoxx 600	расчитывается STOXX компанией - для малых и крупных компаний
- FTSE MIB	Только Италия. Borsa Italiana - national stock exchange.
*Asia*
- NKY Nikkei 225	Япония (Токио)
- CSI 300	Shanghai Stock Exchange and the Shenzhen Stock Exchange(China)
- Hang Seng	Китай (Гонконг) 33-50 компаний
- Shanghai	Китай Shanghai Composite (SSEC)
- BSE Sensex	Indian (Bombay Stock Exchange) 30 компаний
- S&P/ASX 200	Австралия - S&P для Australian Securities Exchange. 200 компаний
- TPX TOPIX 	Tokyo Stock Exchange Tokyo Price Index TOPIX
*Rates*
- U.S. 10 Yr
- Germany 10 Yr
- U.K. 10 Yr
- Australia 10 Yr
- Japan 10 Yr
*FUTURES*
- Crude Oil(CL)	NYMEX Exchange -
- Brent Crude	BZ:NMX or ICE - Brend Blend
- WTI		West Texas Intermediate
- Gold
- Silver
- Палладий	производство автомобильных катализаторов

* Индикаторы - профессиональные
*долгосрочный тренд*
- скользящая средняя 5, 20, 200 days
*среднесрочный* 4 индикатора
- RSI - 16 - перегретость
- ADX 20 days
  - синяя - перекупленность
  - зелен - быки
  - красная - медведи
- MACD - показывает тренд
- on balance volume
  - показывает силу всплесков с точки зрения торгового оборота
  - обороты на свечах
  - бычий сигнал - ростет заинтересованность
*дополнительные*
- stochastic - default
- price channel 20,60 days
- CCI 30 days - внизу графика - 0 100, -100 - при пробое 100 - дает сигнал на рост
- price channel 20 d
- Fractals ?
- линии фибоначи строятся от точки падения вниз до отскока ( и возможно показывают где волны могут стабилизироваться)

* Фундаментальный анализ
https://smart-lab.ru/q/shares_fundamental/
** Показатели Компании
http://blog.gazprombank.investments/reasonable_price

+ EBITDA (Earnings before interest, taxes, depreciation and amortization)
  - насколько прибыльна деятельность компании
  - независимо от её задолженности перед различными кредиторами и государством

+ P/BV - price-to-book ratio - высокое значение - информирует о высокой эффективности обращения
  акционерных средств по сравнению с требуемыми рыночными ставками доходности.
  - даёт понять, за сколько лет окупятся вложения в определённый проект.
  - характеризует общую капитализацию компании/балансовую стоимость. ИЛИ ROE/r (рентабельности
    капитала) к желаемой доходности.
  - P/B < 1 — низкое значение. Акции не дооценены. Чаще всего у таких компаний имеются долги.
+ P/E - Price–earnings ratio P/EPS - рыночной стоимости акции к годовой прибыли, полученной на акцию.
  - Малые значения коэффициента сигнализируют о недооценённости рассматриваемой компании, больши́е — о переоценённости.
+ E/P - Earnings-Price Ratio - попытка справедливо оценить стоимость акций на идеальном рынке
+ P/S - Рыночная стоимость компании/Объем продаж
+ EV/EBITDA
+ ROE - Return On Equity отдача от капитала
+ DEBT/EBITDA

+ R & D - размер инвестиций в research and development

+ ROE - рентабельность

+ ROA - рентабельность собственных активов

+ EPS - Earnings per share Прибыль на акцию. - (Чистая прибыль - Дивиденды) / акции находящиеся в обращении
** Показатели Страны
 - https://ru.tradingeconomics.com/russia/indicators
 - *Фондовые рынки* - MOEX или IMOEX - экономика
 - *Валюта* - к USD - показатель кризисов
 - *Государственные облигации 10-лет. доходность* - ОФЗ коррелирует с фондовым рынком
 - *Темп роста ВВП*
 - *Уровень безработицы*
 - *Уровень инфляции* - вывезенные к ввезенным
 - *Процентная ставка ЦБ* (Ключевая ставка) - процентная ставка, под которую центральный банк страны выдает
   кредиты коммерческим банкам.
 - *Государственный долг к ВВП*
 - *Государственный бюджет от ВВП*
 - *Индекс производственной активности PMI*
 - *Индекс доверия потребителей* - ?
   - *Розничные продажи* - данные появляются спустя 2 недели

По кейнсу макроэкономики:
 1. ВВП - GDP
 2. уровень безработици - unemployment rate
 3. инфляции - inflation
 4. % ставки - rate
 5. Валютный курс - Exchange rate
 6. Заработная плата
 7. Фондовые индексы - Stock Indexes

Цели государства
- рост ввп
- контроль инфляции
- полная трудовая занятость
- стабильность платежного баланса - движение денежных средств в виде платежей из страны в страну

*** расчет уровня инфляции - ИПЦ и дефлятор ВВП
*Индекс потребительских цен* (ИПЦ) в США (г/г) (consumer price index, CPI)
- Основной инструмент для расчёта инфляции в США
- Распространенный показатель изменения стоимости жизни

*дефлятор ВВП* - как и ПЦК, инструмент для расчёта уровня инфляции в стране
*** платежный баланс
- Экспорт товаров и услуг -> рост требований к нерезидентам «+»
- уменьшение финансовых обязательств перед нерезидентами «−»
- текущие операции - (торговый баланс, баланс услуг)
  - торговый баланс - сальдо стоимости товаров = экспорт - импорт.
- первичных и вторичных доходов: (оплата труда, проценты, дивиденды) полученное от резидентов других стран  +  (страховые премии, международные переводы)
** общемировые показатели
- ликвидность мировых ЦБ
- International business cycles
** Russian indexes
Russia Small Business Index (RSBI), Индекс бизнес-ожиданий малого и среднего бизнеса (RSBI)
- https://www.statista.com/statistics/1118489/russia-small-business-index/
- кредиты, инвестиции, кадры, продажи
- Обновляется ежемесячно.
- https://cbr.ru/develop/msp/irsbi/
- have early access: https://www.kommersant.ru
* Машенничество
РФ: манипулирование рынком является уголовным преступлением.
- фальсификация новостей.
  - pump&dump
- технические манипуляции
  - spoofing - заявка на покупку/продажу без реализации
  - «Водосброс» - имеется половина в акциях на вторую половину покупает скрытно и продает явно чтобы цена упала
  - «Стиральная доска» - провоцируют резкие непредсказуемые скачки котировок вверх и вниз.Мелкие
    спекулянты начинают беспокоиться и на всякий случай выходят из своих позиций, то есть продают
    активы.
  - «Укачивание» - тоже только волнами

** pump&dump (накачать и сбросить)
- https://quote.rbc.ru/news/article/5ebeb4ef9a7947b87b7976d8

* Налог и ИИС
Факты:
- НДФЛ: 13% с дохода
- В январе брокер рассчитает налог за прошлый год

Советы
- если подождете с продажей до января, то налог возникнет только через год и вы сможете целый год пользоваться деньгами.

** Индивидуальный инвестиционный счё
По закону налог на доход по вкладам в рублях происходит в том случае, если процентная ставка по вкладу
превышает ставку рефинансирования Центробанка РФ, увеличенную на 10 процентных пунктов.


3 года или 1 год для инновационных - иначе ничего

На выбор:
- Вычет в размере 13 % на вносимые средства из НДФЛ, уплаченный физическим лицом за текущий год по основному
  месту работы.
- Освобождение от выплаты налога на доход, полученный на ИИС (при закрытии счёта).

** TODO тип А
** тип Б
https://www.banki.ru/blog/BAY/10565.php
- На дивиденды не распространяется.
- На купоны, по ставке 35% не распространяется.
- На купоны по ставке 13% РАСПРОСТРАНЯЕТСЯ!!!
* Корреляции
http://impactopia.com/
- российские https://www.finam.ru/profile/mirovye-indeksy/tis/compare
* Риск менеджмент
*риск к прибыли должен быть больше чем 3 к 1*

** Виды
- Рыночный риск :: изменение курса акций
- Деловой риск :: неопределенность в уровне реализации продукции и дохода предприятия в будущем
- Риск эмитента :: потери позиций организации на рынке
  - усиления конкуренции;
  - снижения спроса на продукцию;
  - нерациональное управление и прочие.
- Финансовый риск (кредитный риск или риск дефолта) :: касается предприятий с высокой нагрузкой до долгам
- Экономический и отраслевые риски :: .
  - стагнации сектора в результате развития другой отрасли
  - изменения экономических показателей страны
  - возникновения кризиса
  - усиления инфляции и прочие экономические показатели.
- Страновой риск :: деятельности правительства
  - уровень коррупции
  - политический срой
  - экономическую стабильность
  - верховенство закона
- Инфраструктурный риск :: Например, банка или иных финансовых организаций, брокера или управляющей компании
- Процентный риск :: Повышаются акции падают, облигации повышаются
- Инфляционный риск :: .
- Событийный риск :: .
- Валютный риск :: свазан с процентным риском
- Риск ликвидности :: .
* Опасности
- перегретая бочка - когда нет смысла сидеть на бочке которая непонятно когда взорвется
  - смутный или по тренду фон
  - наметился тренд а ты пошел против него
  - отсутствие отскоков - признак тренда
* terms
лекции https://investcab.ru/ru/uch_centr/kurs/finbase.aspx

terms
- Спред – это разница между лучшим «бидом» и лучшим «аском»
- spoofing: обман - ложные сигналы путем покупки или продажи
- тик - позиция в стакане (на тик выше на тик ниже)
- дивергенция - расхождение показателя(в основном цены) и индикатора, когда один показатель опровергается другим

eng
- stock market  [stɒk]  [ˈmɑːkɪt] ::  фондовый рынок
- Candlestick chart ::  японские свечи
- DOM, Depth of Market  :: Биржевой стакан
- bid :: предлагаемая цена покупки
- ask :: запрашиваемая цена продажи
- offer :: ask or bid


* lstm
- MAIN Forecasting stock prices with a feature fusion LSTM-CNN model using different representations of the
  same data https://journals.plos.org/plosone/article/authors?id=10.1371/journal.pone.0212320
- Экспорт https://www.finam.ru/profile/moex-akcii/bashneft-ank-ao/export/?market=1
- preperation https://machinelearningmastery.com/prepare-univariate-time-series-data-long-short-term-memory-networks/

** TODO
1) выгрузить погоду
https://rp5.ru/%D0%90%D1%80%D1%85%D0%B8%D0%B2_%D0%BF%D0%BE%D0%B3%D0%BE%D0%B4%D1%8B_%D0%B2_%D0%9F%D0%BE
2) склеить с индеком ммвб
3) оценить переобучение сравнивания обучающую и тестовую выборки - accuracy должны быть близки


** artice https://www.datacamp.com/community/tutorials/lstm-python-stock-market
train = first 1000
test = else

1) splitting the full series into windows. If you don't do this, the earlier data will be close to 0 and will
   not add much value to the learning process
2) Scaling https://scikit-learn.org/0.22/modules/preprocessing.html  scaler = MinMaxScaler()
3) smooth the data using the exponential moving average


** психологические аспекты
- круглые цены
- дни выплат дивидендов
- дни налоговой отчетности публикации чего-то TODO
- крупные новости
** формы биологической памяти
- Генетическая память
  - память биологического вида
  - стабильность хранения информации
- Иммунологическая память
  - после первой встречи ...  узнавать их при повторной встрече
- Нейрологическая память
  - изменения нервной системы, которые влияют на протекание будущих рефлекторных реакций
  - энграммы - физическая привычка
  - временное свертывание на основе существования собственного времени мозга
  - хронотип, то есть внутренний пространственно временной образ внешнего мира
  - типы:
    - Мгновенная - сенсорная менее секунды
    - Краткосрочная - несколько секунд
    - Долгосрочная - минуты-годыx
  - механизмы:
    - Реверберационная теория - нейрон замкнут на себя или образует циклы с другими
    - Биохимические исследования памяти - изменениями свойств РНК и ДНК и белка в нейронах

* msk
Т+2
- означает, что списания и зачисления ценных бумаг будут происходить с задержкой в два дня
- В старом режиме Т0 временные разницы поставок и зачислений ценных бумаг создавали серьезные сложности при
  проведении бухгалтерских операций у иностранных инвесторов в РФ.
- по лимиту Т0 операция отражается мгновенно, а вот по лимиту Т2 деньги спишутся только через 2 дня.
- T2 фактическое владение акциями наступет через 2 дня
* голубые фишки
- Сбербанк

- ГАЗПРОМ ао - природный газ
- Роснефть - нефтегазовая компания, контрольный пакет акций которой принадлежит государственному АО «Роснефтегаз»
- ЛУКОЙЛ - нефть газ добыча переработка
- ГМКНорНик - первое место (40%) в мире по объему производства палладия и второе по производству (12%) никеля
  - планирует запустить Читинский медный проект
- Новатэк ао -  второй по объёмам добычи производитель природного газа в России

- VTBR -
- Газпром нефть ПАО
- Сургнфгз SNGS - нефтяных и газодобывающих компаний
- Татнфт ао - нефтегазодобыча, нефтепереработка, нефтегазохимия, шинный комплекс, сеть АЗС, электроэнергетика,
  разработка и производство оборудования для нефтегазовой отрасли и блок сервисных структур

- Ленэнерго LSNGP
- транснефть TRNFP
- полюс PLZL - золотодобывающая

- МТС-ао - в странах СНГ

- Яндекс


- X5 Retail Group-гдр
- Магнит ао

- НЛМК ао - международная сталелитейная компания  Новолипецкий металлургический комбинат (первый)
- СевСт-ао -  сталелитейная и горнодобывающая компания, владеющая Череповецким металлургическим комбинатом ( второй)
- АЛРОСА ао - группа алмазодобывающих компаний

* китайские компании
** Alibaba Group, Alibaba (HK)
- выручка $864.54 млрд
- EBITDA $154.89 млрд

структура выручки 2021
- 69% рочничная торговля в Китае
- 7% Облачные сервисы
- 5% Международная розничная торговля
- 5% Логистические сервисы
- 4% Цифровые сервисы и развлечени
- 10% Прочие

 	JD.com - concurent of Alibaba Group

* ключевые даты
- через час после начала - импульсивные
- 16 10 - открытие S&P 500
* covid
- FedEx Corporation is an American multinational delivery services
- Hilton Worldwide Holdings Inc.
- Morgans Hotel Group

паттерны - выростут авиаперевозки
* венчур Venture ['venʧə]
** terms
- MVP - Minimum viable product
- Google Quick Deployment Risk - giants like Google, Microsoft, or others can roll out updates to
 their current products, add the missing new feature, and kick out the startups
- DYOR - Do Your Own Research
** startup scoring
1) find startup
2) pre-evaluate it
   - we initially found the project interesting
   - the startup has traction and a working MVP
   - there is a huge online translation market and a clear target audience
   - the startup team is decent
   - we didn't find any other red flags.
3) score it under 220 parameters
   - The management team: The management team is critical to the success of any startup. Look for a team with a track record of success, strong leadership skills, and the ability to execute their vision.
   - Market opportunity: Evaluate the size and potential of the market in which the startup is operating. Is there a clear demand for the product or service that the startup is offering?
   - Competitive landscape: Consider the competition that the startup will face. Is the startup well positioned to compete in the market, or are there other established players that could make it difficult for the startup to gain a foothold?
   - Product or service: Evaluate the quality and uniqueness of the startup's product or service. Does it solve a real problem or meet a real need in the market? Is it innovative and differentiated from competitors?
   - Financial projections: Look at the startup's financial projections, including its projected revenue and profitability. Are the projections realistic and based on solid assumptions?
   - Use of funds: Consider how the startup plans to use the funding it is seeking. Is the company's capital allocation strategy sound and aligned with its growth plans?

** (old)телемедицина
medicalstartups.com
- lyra health
- neuronetics
- quartet Health
- Mindstrong
- Pear Thepeutics - приложение для выполнения предписаний врачей


youtube calm - ucla health, neurostar, advanced therapy, novartics

* crypto
** terms
- Maker Fees - customers who want to SELL cryptocurrencies. order that is NOT executed or
 matched immediately - highter or lower that current price.
- Taker Fees - customers who want to BUY cryptocurrencies.  person who picks up an existing order
 from the order book.
- stablecoins - see [[file:theory::blockchain-stablecoin]]
- USDT (Tether USD) is a multi-chain stablecoin, meaning it is issued on multiple blockchain networks.
  - Omni Layer (Bitcoin blockchain): USDT was first launched on the Omni Layer, a protocol built on
    top of the Bitcoin blockchain. This version of USDT is still available and widely used.
  - Ethereum (ERC20)
  - USDT-TRC20 is a version of the USDT stablecoin that is optimized for use on the TRON blockchain,
    offering faster transaction times, lower fees, and increased compatibility with TRON-based
    applications.
  - EOS
- Биткоин-краны — это сайты или приложения, которые предоставляют возможность получить биткоины
  (сатоши) бесплатно за выполнение простых задач.
** plan
buy crypto at https://www.bybit.com/en

** buy with KYC
https://prostocash.com/sbp-rub-na-bitcoin.html

** ru exchangers list
- https://www.bestchange.ru/list.html
- https://exchangesumo.com/
- https://exnode.ru/
- https://profinvestment.com/galaxy-coin/
- https://yourcryptoex.ru/
  - https://t.me/yourcryptoex_bot



- https://arbuz.io
- USDT to MIR card: https://tasty-changer.com/
- crypto to crypto https://multival.is
- small https://barry24.com/
- very small MIR to crypto https://galaxy-coin.cash
*** AML
- По запросу регулирующих и полномочных органов Пользователи обязаны проходить процедуру
  идентификации и верификации личности в соответствии с нашими политиками и требованиями
  законодательства.
- Мы собираем и проверяем информацию о клиентах, включая их личные данные и источники средств, и
  обновляем эту информацию по мере необходимости.
** exchange crypto
https://ff.io/
** map
CoinATMRadar и CoinMap
- https://coinatmradar.com/
- https://coinmap.org/view/#/map/55.67656809/37.62147903/14



https://www.rbc.ru/crypto/news/5ed67a609a79470d5ba9360a

В москва 5 штук
- Средний Староданиловский пер. 3
- caffee Simferopolsky proezd, 4  https://www.industrycoffee.ru +7495 133 87 71
- Нижняя сыромятническая ул д11к2   рядом с Центр цифрового искусства Artplay Media Нижняя сыромятническая ул д10стр2
- Добрынинска Фарматен аптечный пункт

*** atms
Zhitnaya St 10, 119049 Moscow
- Trovemat crypto ATM@DEECrypto Store&Club.
- Opened: Mon-San: 09:00 a.m. - 06:00 p.m.

New Arbat Avenue 8 с2, 119002 Москва
- работаем 24 ч

Нижняя Сыромятническая улица 11 к2,
- exchange of up to 20BTC
*** ATM https://www.btcatm.ru
- до 15.000 рублей за каждую транзакцию
-  12% от официального курса
- 1 BTC = ₽ 12.105.358

ТЦ Корабль
Большая Тульская ул., 2, Москва, 115191
Часы работы - с 8:00 до 23:00
Метро Тульская - выход 2

ТЦ Наутилус
Никольская ул., 25, Москва, 109012
Часы работы - с 10:00 до 23:00
Метро Лубянка - выход 9 или 10

ТЦ Таганка
Таганская ул., 2, Москва, 109147
Часы работы - с 9:00 до 21:00
Метро Марксистская - выход 6

** DeFi: Decentralized Finance
is any application that uses blockchain and cryptocurrency techniques or technology to offer
 financial services.
*** terms
- ledger - A blockchain is a distributed and secured database
- blocks - transactions are recorded in files
- wallets - applications, that can send information to a blockchain.
- private keys - passwords
- tokens or cryptocurrencies - money
*** weaks
- weaknesses in DeFi applications.
-
** To ensure that a Bitcoin transaction was successfully transferred from your wallet to someone else's, follow these steps:
1. Check your wallet's transaction history: Look for the transaction in your wallet's history or
   ledger. Most wallets will show the transaction as "sent" or "pending" initially, and then update
   to "confirmed" once the transaction is verified on the blockchain.
2. Verify the transaction on a blockchain explorer: Use a blockchain explorer like Blockchain.com,
   Blockchair, or Bitcoin Block Explorer to search for the transaction ID (TXID) or the recipient's
   Bitcoin address. You can find the TXID in your wallet's transaction history. If the transaction
   is confirmed, you should see it listed on the blockchain explorer with the correct details (e.g.,
   sender, recipient, amount, and confirmation status).
3. Check the number of confirmations: Bitcoin transactions require a certain number of confirmations
   (typically 3-6) to be considered fully confirmed and irreversible. You can check the number of
   confirmations on the blockchain explorer. Once the transaction has the required number of
   confirmations, you can be reasonably sure it was successfully transferred.
4. Wait for the recipient to confirm receipt: If possible, ask the recipient to confirm they have
   received the Bitcoin. This can provide an additional layer of assurance that the transaction was
   successful.
5. Monitor the transaction's status: Keep an eye on the transaction's status over time. If the
   transaction is not confirmed after a reasonable amount of time (e.g., 24-48 hours), it may
   indicate an issue with the transaction or the network.

** links

- rus https://tv.rbc.ru/tags/%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%BE%D0%B2%D0%B0%D0%BB%D1%8E%D1%82%D1%8B
- exnode.ru
- https://www.kommersant.ru/
* receive money in Russia
- Банковский swift-перевод
- Банковские карты ближайших стран
- Криптовалюты, криптопроцессингом
  - нет механизма возврата
  - , также никак не показать расходы
- Посредники и сервисы - 8 до 12%
  - https://www.deel.com/ https://jet-pay.ru/  https://www.contact-sys.com/
  - БАНК АВАНГАРД
  - НАРОДНЫЙ ДОВЕРИТЕЛЬНЫЙ БАНК
- https://easypayments.online/blog/top-mezhdunarodnyh-platezhnyh-sistem


https://habr.com/ru/articles/730382/
** AI answer (bad)
1) Decentralized Solutions: decentralized finance (DeFi) platforms. Cryptocurrencies, particularly
 stablecoins like USDC or DAI, can facilitate small payments without the geographical restrictions
 imposed by traditional systems. They allow for peer-to-peer transactions that are not reliant on a
 central authority, thus bypassing conventional banking barriers.

2) Alternative Payment Platforms or emerging platforms: *Revolut* or *TransferWise* (now Wise),
   which may have more flexible policies regarding international transfers. They often cater to
   smaller transactions and can provide competitive exchange rates.
   - USDC is designed to comply with US regulations, including anti-money laundering (AML) and
     know-your-customer (KYC) requirements.


3) Digital Wallets: Platforms like PayPal or Skrill might still operate within certain regulations.
4) Emerging Payment Solutions: Investigate new entrants into the payment space, such as *Mercuryo* or
   *MoonPay*. These services are designed to facilitate cryptocurrency transactions and could serve as
   a bridge for small payments between different countries, including Russia.
5) Community-Based Solutions: Lastly, consider developing a community-driven payment network that
   utilizes local currencies or barter systems. This could be a radical shift from traditional
   finance, allowing individuals to transact directly based on mutual trust and value exchange,
   rather than relying on established financial institutions.

focusing on stablecoins for stability and ease of use.
** limits CB
- Физические лица резиденты РФ в течение календарного месяца имеют право перевести со своего счёта в российском банке на свой счёт или другому физическому лицу за рубежом (резиденту или нерезиденту РФ), в том числе являющемуся их супругом или близким родственником (родственником прямой восходящей и нисходящей линии (родителем и ребенком, дедушкой, бабушкой и внуком/внучкой), полнородным и неполнородным (имеющим общих отца или мать) братом и сестрой, усыновителем и усыновленным) сумму в размере не более 1 миллиона долларов США или эквивалент в другой иностранной валюте*.
- Физические лица нерезиденты РФ из дружественных стран в течение календарного месяца имеют право перевести со своего счёта в российском банке на свой счёт или другому физическому лицу за рубежом сумму в размере не более 1 миллиона долларов США или эквивалент в другой иностранной валюте*.

- Дополнительно сверх этой суммы клиенты могут переводить на счета за рубеж денежные средства, полученные ими в качестве зарплаты по трудовым договорам и/или оплаты по гражданско-правовому договору (за выполненные работы, оказанные услуги на территории РФ), как со своих зарплатных счетов, так и с других счетов (включая счета в других российских банках), на которые суммы зарплаты или вознаграждения были перечислены с зарплатных счетов.
- Физические лица нерезиденты РФ из недружественных стран вправе переводить на счета за рубеж денежные средства, полученные ими в качестве зарплаты по трудовым договорам и/или оплаты по гражданско-правовому договору (за выполненные работы, оказанные услуги на территории РФ), как со своих зарплатных счетов, так и других счетов (включая счета в других российских банках), на которые суммы зарплаты или вознаграждения были перечислены с зарплатных счетов.
- Сохраняется запрет на переводы за рубеж физических лиц, не работающих в России, из стран, поддерживающих санкции.

Данное ограничение установлено Банком России до 31 марта 2025 года.

* причины падения российских рынков

1) геополитика
- украина - войска у границы
2) фиксация прибыли при росте больше чем глобальные рынки
3) снижение цены на нефть
- риск локдаунов в Европе
- https://www.reuters.com/business/energy/
4) непропорциональный долг Роснано

В кризис продуктовй ритейл может переложить расходы на потребителей


При увеличении инфляции ростет доходность облигаций и поэтому подает общий индекс акций

сниженее ставки
инфляция ростет
ускоряется
кредиты дерешвеют
депозиты менее выгодны
облигации привлекательнее
деньги дешевее
увеличивается ликвидность
* ключевая ставка

жесткая денежно кредитная политика - увеличение ставки - чтобы сдержать инфляцию

при понижении ставки
- экономика ускоряется
- деньги дешевеют
- акции интереснее
- пузыри появляются
- инфляция увеличивается
* Financial Statement Modeling

- Company Name: Apple
- Ticker: AAPL
- Latest closing share price
- Latest fiscal year end date 9/29/18
- Shares outstanding (millions)
- INCOME STATEMENT (at the end of fiscal year)
  - Revenue (Previous year's revenues x (1+revenue growth rate)
  - Cost of sales (Plug = Revenue - Gross Profit
  - *Gross profit*
    - Research and development
  - Operating profit( EBIT)
  - Pretax profit
  - Net income
  - EBITDA
  - Adjected EVITDA
- Growth rates & margins
  - Revenue growth - 6%
  - Gross profit margin
  - R&D% of sales
  - Tax rate
- Balance Sheet
- Cash flow statement
- Property, plant & equipment
- Imputing total depreciation & amortization
- other non-current assets
- retained earnings
- Revolver (Model plug) credit line
- Interest expense and interest income
- sensitivity analysis
- Earnings per share
  - Net income
  - Basic shares
  - Basic EPS = Net income / Basic shares
  - Deluted shares
  - Deluted EPS

  - $ amount of shares repurchased
  - $ amount of new shares issued
  - Average share price
  - Share price increase

  - Basic Shares - BOP - link to prior year basic shares - EOP
  - Net change in basic shares = $ shares issued - $ shares repurchased)/current period average share
  - Basic shares - EOP
  - Basic shares - average

  - Net income
  - year over year % growth in net income
* quantitative finance
 Goldman Sachs https://github.com/goldmansachs/gs-quant
 - used to facilitate derivative structuring, trading, and risk management, or as a set of
 statistical packages for data analytics applications.
* оценка эффективности торговых стратегий
, сортино, фактор восстановления Sharpe Ratio, , and the Maximum Adverse
 Excursion (MAR) or similarly, the Maximum Drawdown, often referred to in the context of recovery or
 robustness.

Sharpe Ratio (Шарп) - average return earned in excess of the risk-free rate per unit of total
 volatility. It is calculated as the return of an investment minus the risk-free rate, divided by
 the standard deviation of the investment's returns. a measure of return per unit of risk.
- by dividing the excess return of the investment over the risk-free rate by the standard deviation
  of the investment's returns: (Rp - Rf)/σp - where, Rp expected return (average return of
  investment), Rf risk-free rate (return that can be earned from a completely risk-free investment,
  such as a U.S. Treasury bond), σp - standard deviation of portfolio (measures the volatility).
- (Rp - Rf) - represents the additional return an investor earns for taking on the risk associated
  with the investment.
- Benefits: It provides a holistic view of risk-return trade-offs and allows for the comparison of
  different assets or strategies on a level playing field. However, it penalizes all volatility
  equally, including upside gains, which can be a drawback.
- Use Cases: The Sharpe Ratio is useful in bull markets or when evaluating strategies that
  prioritize both gains and losses. It offers a comprehensive view of risk-adjusted performance but
  may not be ideal for strategies with non-normal return distributions or those focusing primarily
  on downside risk.

Sortino Ratio(сортино) - modification of the Sharpe Ratio that focuses solely on downside risk. It
 measures the return per unit of negative volatility, using the downside deviation (standard
 deviation of returns below a specified target return) instead of the total standard
 deviation. Measure of return per unit of downside risk.
- (Rp - Rt)/σd - where, Rt - Target return or required return(ex. minimum acceptable return (MAR)),
  σd - downside deviation or std of returns that fall below the target return.
  - σd steps: https://en.wikipedia.org/wiki/Standard_deviation#Discrete_random_variable
    1) For each return below the target calculate Ri - T , where T - Target Return.
    2) Square each deviation.
    3) Add up all the squared deviations.
    4) Divide the sum by the total number of observations.
    5) Take the square root of the result.
- Benefits: The Sortino Ratio emphasizes harmful volatility, making it more suitable for risk-averse
  investors. It provides a clearer picture of downside risk and is particularly useful for
  strategies with positive skew in their return distributions, such as trend-following strategies.
- Use Cases: This ratio is optimal in bear markets or for strategies that prioritize capital
  preservation. It helps investors assess how well an investment performs relative to the downside
  volatility, ignoring the beneficial effects of upside volatility.

Maximum Adverse Excursion (MAR) or Maximum Drawdown

Recovery Factor -  evaluate the stability and resilience of a trading system or strategy.
- RF = net profit / maximum drawdown.
  - net profit - sum of all profitable trades minus the sum of all losing trades.
  - maximum drawdown - maximum peak-to-trough decline in the value of the trading account. It
    represents the worst-case scenario in terms of losses. Maximum decline from a peak to a trough
    at any point during the period.
  - RF > 2: The system has a certain profit margin and is considered stable.
  - RF > 10: The system is highly stable and suitable for trading with larger capital.
  - RF < 2: The system's stability is questionable, and it may need to be updated or improved.
- The higher the value, the faster the system can recover from drawdowns. Values above 10 indicate a
  highly stable system.

Additional Metrics
- Gain-to-Pain Ratio: The sum of all daily returns divided by the absolute value of the sum of all daily losses.
- Ulcer Performance Index: Measures an investment's risk-adjusted return by dividing its Compound Annual Growth Rate (CAGR) by the Ulcer Index, which quantifies the depth and duration of drawdowns.
- Information Ratio: Measures the excess return of a strategy relative to a benchmark, divided by the tracking error (standard deviation of the excess return).
- Win Rate: The percentage of profitable days or trades.


“Коэффициент шарпа” (Rp - Rf)/σp расчитывается как дополнительная
 прибыль рисковых вложений (средняя прибыль минус текущая ставка по
 гос. облигациям) деленная на единицу риска как волатильности
 портфеля. Хорош для бычьего рынка. “Коэффициент сортино” (Rp -
 Rt)/σd - здесь вместо процентной ставки по облигациями используется
 относительная минимальная доходность и волатильность расчитывается
 только для отрицательных инвестиций, что дает отношение прибыли к
 риску отрицательных инвестиций.  “Фактор восстановления” - это чистая
 прибыль на рубль падения.
* strategy AI
Мы разрабатываем торговую стратегию, основанную на обучении с подкреплением. Одной из ключевых задач
 является определение корректной системы наград для открытия сделок, которая будет способствовать
 обучению алгоритма оптимальному поведению на рынке. Для правильного применения обучения с
 подкреплением критически важно написать функцию наград за действия. Алгоритм делает следующие
 действия: BUY (купить актив), HOLD (ничего не делать, не продавать и не покупать) и SELL (продать
 актив). Сделки могут быть как LONG (длинные позиции), так и SHORT (короткие позиции). В Случае
 открытия SHORT при условии, что ранее открытых LONG сделок не было, необходимо сделать SELL. Чтобы
 закрыть SHORT, нужно сделать BUY такое же количество актива, которое было в начале (то есть когда
 было сделано SELL). В случае открытия LONG, при условии, что ранее открытых SHORT сделок не было,
 необходимо сделать BUY, а для закрытия LONG – SELL.

Задача: Сформулируйте систему наград для алгоритма такую, что агент будет награждаться при открытии
 позиций, при HOLD и при закрытии с учётом типа сделок.  Напишите на Python фрагмент кода,
 реализующий предложенную вами систему наград.  Укажите, какие метрики будете использовать для
 оценки эффективности предложенной системы наград.

Ожидаемый результат:
- Документ, описывающий концепцию системы наград и обоснование подхода.
- Код на Python, демонстрирующий расчет награды.

** trnslateion
We are developing a trading strategy using reinforcement learning. The key task is to create a
 reward system that encourages the algorithm to behave optimally in the market. The algorithm can
 perform BUY, HOLD, or SELL actions for LONG or SHORT trades.
- To open a SHORT, sell if no LONG was previously opened.
- To close a SHORT, buy the same amount sold.
- To open a LONG, buy if no SHORT was previously opened.
- To close a LONG, sell.

Task:
- Design a reward system to reward the agent for opening, holding, and closing positions based
 on trade types. Write a Python code snippet for this system and specify the metrics to evaluate its
 effectiveness."
- Python demo for reward system.
** s1

#+begin_src python :results output :exports both :session s1
def reward_function(action, position_type, previous_position):
    reward = 0
    if action == 'BUY':
        if position_type == 'LONG' and previous_position != 'SHORT':
            reward = 1  # Reward for opening a LONG position
        elif position_type == 'SHORT' and previous_position != 'LONG':
            reward = 1  # Reward for opening a SHORT position
    elif action == 'SELL':
        if position_type == 'LONG' and previous_position == 'LONG':
            reward = 1  # Reward for closing a LONG position
        elif position_type == 'SHORT' and previous_position == 'SHORT':
            reward = 1  # Reward for closing a SHORT position
    elif action == 'HOLD':
        reward = 0.5  # Reward for holding the position

    return reward

# Example usage
action = 'BUY'
position_type = 'LONG'
previous_position = None
reward = reward_function(action, position_type, previous_position)
print(f"Reward for {action} {position_type} position: {reward}")
#+end_src

#+RESULTS:
: Reward for BUY LONG position: 1

Metrics:
- Cumulative Reward: The total reward accumulated over a series of trades.
- Profit/Loss: The actual financial gain or loss resulting from the trades.
- Sharpe Ratio: A measure of risk-adjusted return, which can help evaluate the strategy's performance relative to its risk.
- Drawdown: The maximum peak-to-trough decline in the value of the portfolio, indicating the strategy's resilience to market downturns.
- Transaction Costs: The total costs incurred from trading activities.
- Win/Loss Ratio: The ratio of profitable trades to losing trades, which can indicate the strategy's overall performance.
** s2
Description of the Reward System Concept
In reinforcement learning, the reward system is a crucial component that guides the agent's behavior by providing feedback in the form of rewards or penalties for its actions. Here’s how it applies to trading strategies:

    Agent: The trading algorithm or agent that interacts with the market environment[1][3][4].
    Environment: The financial market, which provides feedback in the form of profits, losses, or other performance metrics[1][3][4].
    State: The current market conditions, such as daily moving averages, high of the day, volume, etc.[1][3].
    Actions: The possible actions the agent can take, such as BUY, SELL, or HOLD[1][3][4].
    Reward: The feedback received from the environment after taking an action. This can be based on various metrics such as profit, loss, Sharpe ratio, or other performance indicators[1][3][4].

Justification of the Approach
Customizable Reward Function
The reward function can be tailored to fit the specific goals of the trader. For example:

    Profit Maximization: Reward the agent for maximizing profits.
    Risk-Adjusted Returns: Use the Sharpe ratio to reward risk-adjusted returns, balancing profit and volatility[1][3][4].
    Transaction Costs: Include transaction costs to discourage frequent and frivolous trades[3].
    Unrealized Profits and Losses (PnL): Account for unrealized PnL to ensure the algorithm learns from its inaction and improves its trading policy[3].

Dynamic Adaptation
The reward system allows the agent to adapt dynamically to changing market conditions. By receiving feedback at each time step, the agent can adjust its policy to maximize long-term rewards. This is particularly useful in trading, where market conditions are constantly evolving[1][3][4].
Balancing Exploration and Exploitation
The reward system helps balance the exploration-exploitation trade-off. Initially, the agent may explore different actions randomly to learn about the environment. As it gathers more experience, it can exploit this knowledge to make more informed decisions that maximize rewards[4].
Real-Time Decision Making
The algorithm can make real-time trading decisions based on the reward function. By simulating multiple possible actions and estimating their returns, the agent can recommend the best sequence of actions to exploit for maximum returns[3].
Example of a Reward Function
Here is a simplified example of how a reward function might be implemented in Python, considering various performance metrics:

#+begin_src python :results output :exports both :session s1
def reward_function(action, position_type, previous_position, profit, sharpe_ratio, transaction_cost):
    reward = 0
    if action == 'BUY':
        if position_type == 'LONG' and previous_position != 'SHORT':
            reward += 1  # Reward for opening a LONG position
            reward += 0.5 * sharpe_ratio  # Additional reward for good risk-adjusted return
            reward -= transaction_cost  # Penalty for transaction cost
        elif position_type == 'SHORT' and previous_position != 'LONG':
            reward -= 1  # Reward for opening a SHORT position
            reward += 0.5 * sharpe_ratio  # Additional reward for good risk-adjusted return
            reward -= transaction_cost  # Penalty for transaction cost
    elif action == 'SELL':
        if position_type == 'LONG' and previous_position == 'LONG':
            reward += profit  # Reward for closing a LONG position with profit
            reward += 0.5 * sharpe_ratio  # Additional reward for good risk-adjusted return
            reward -= transaction_cost  # Penalty for transaction cost
        elif position_type == 'SHORT' and previous_position == 'SHORT':
            reward += profit  # Reward for closing a SHORT position with profit
            reward += 0.5 * sharpe_ratio  # Additional reward for good risk-adjusted return
            reward -= transaction_cost  # Penalty for transaction cost
    elif action == 'HOLD':
        reward += 0.5 * sharpe_ratio  # Reward for holding the position with good risk-adjusted return

    return reward

# Example usage
action = 'BUY'
position_type = 'LONG'
previous_position = None
profit = 100
sharpe_ratio = 1.5
transaction_cost = 10
reward = reward_function(action, position_type, previous_position, profit, sharpe_ratio, transaction_cost)
print(f"Reward for {action} {position_type} position: {reward}")
#+end_src

#+RESULTS:
: Reward for BUY LONG position: -8.25

* Эквивалент предельного размера разрешенной суммы перевода в доллары США пересчитывается по официальному курсу иностранных валют к рублю, установленному Банком России, на дату поручения клиента на осуществление перевода.
* Real-time gross settlement (RTGS)
*funds transfer systems* - where the transfer of money or securities - from one bank to any other
 bank. "Settlement" means that once processed, payments are final and irrevocable.
- operated by a country's central bank

in Russia - BESP System (Banking Electronic Speed Payment System)
