-*- mode: Org -*-
https://dis-group.ru/company-news/articles/kto-takoj-cdo-chief-data-officer-ili-chief-digital-officer/
- как организовать аналитику в данных в компании оффицер данных,

Евсеева Анна
Гузель Халикова

- витрина MART_NORMA_AUTO
- отчет по сделкам в Норме

отчет о состоянии кредитного портфеля для андерайтора в ЦФТ в групповых запросах

Андерайтер не успев рассмотреть получает информацию что клиент отказался и ставит код отказа 091 или 01
- поэтому эти заявки нужно исключить из отказанных, так как их даже не проверил андеррайтер
* MART_NORMA_AUTO
SRC_BANK = РНБ
SRC_SYSTEM=2
DEL_KIND_CRED_NAME = Авто-РНБ
* переписка
Subject
- Зависимости по решениям андеров
- Повышение эффективности на этапе андеррайтинга
* задача

цель: автоматизировать андеррайтора - найти принаки указывающие на высокую вероятность
1) акцентируем внимание на одобренных, потому что не знаем наскольк оплохие плохие.
2) учитываем просрочку



** *моделирование андерайтора* - всегда одобряет или чаще всего
цель: клиент хороший и его одобряет - в каком диапазоне 
выделить 

Цель: Найти сегмент в котором андерайтер всегда одобряет заявки


из того что андерайтор отказывает мы еще одбираем среди них которые можно принять.

хороший и не дефолтных - без фы отклоненных заявок - потому что мы не знаем насколько они плохие.
- 

- все одобренные андеррайтором не обязательно окончательное решение

- РНБ-авто - наши автокредиты src_bank='РНБ'

Вопросы
- можем ли мы считать числовые скоринги - чем больше тем лучше?



** признак дефолта на тех которые одобрены

чем отличаются которые выходят на просрочку
* созвон
1) набор атребутов

3) отказ клиента на нашей стороне и отказ клиента на их стороне

1) data_mart_ полцчить отчет

+ красное отклонены + всего заявок серое эквифакс + синее акцентованные/ меньше 500 не интересует + выпущенные зеленым + желные отклонено самим клентом


синтетические

заявленное


анкетные данные не берем
- доход клиента

посмотреть с высоким скоринговым балом

кредитную историю - хорошую и нейтральную  и в сторону меньшего зла - в сторону скорингового бала - МБКИ - ВОЗРАСТ


СрД
Возраст
Платеж доход
скоринговыебалы
и первоначальный взнос
сумма кредита
